channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: kemal
  host: postgres
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
decrypto_polling: false
port: 3001
domain:
